---
# Author: rfrancisco6
# config_ops445.yml
- name: Configure VM for OPS445 - lab8
  hosts: vmlab
  user: student
  become: yes
  vars:
    seneca_id: "rfrancisco6"

  tasks:
    # Update Apache (httpd)
    - name: Update Apache httpd
      yum:
        name: httpd
        state: latest
    
    # Install EPEL repository
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: latest
    
    # Remove 'tree' package
    - name: Remove tree package
      yum:
        name: tree
        state: absent
    
    # Set hostname to Seneca ID
    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"
    
    # Create user with Seneca ID and sudo access
    - name: Create user with Seneca ID
      user:
        name: "{{ seneca_id }}"
        state: present
        groups: wheel
        append: yes
    
    # Configure sudo access without password
    - name: Setup sudo access without password
      copy:
        dest: "/etc/sudoers.d/{{ seneca_id }}"
        content: "{{ seneca_id }} ALL=(ALL) NOPASSWD: ALL"
        mode: 0440
        validate: 'visudo -cf %s'
    
    # Create .ssh directory for the new user
    - name: Create .ssh directory
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: 0700
    
    # Copy SSH public key for password-less login
    - name: Setup SSH public key for password-less login
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: 0600
    
    # Create lab directory structure using a loop
    - name: Create directory structure for labs
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: 0755
      loop: "{{ range(1, 9) | list }}"
